apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pacman
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pacman
  namespace: pacmanv2
subjects:
- kind: ServiceAccount
  name: pacman 
  namespace: pacmanv2
roleRef:
  kind: ClusterRole
  name: pacman
  apiGroup: rbac.authorization.k8s.io
