apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 2
  labels:
    app: haproxy
  name: haproxy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: haproxy
    deploymentconfig: haproxy
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: haproxy
        deploymentconfig: haproxy
    spec:
      containers:
      - image: registry.connect.redhat.com/haproxytech/haproxy:latest
        imagePullPolicy: Always
        name: haproxy
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/haproxy
          name: config
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: 01-haproxy
            path: haproxy.cfg
          name: haproxy
        name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
