apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/deployment.yaml
- base/service.yaml
- base/configMap.yaml

patchesStrategicMerge:
- overlays/production/deployment.yaml
- overlays/dev/deployment.yaml
- overlays/stage/map.yaml
