apiVersion: v1
kind: Namespace
metadata:
  name: simple-app
---
apiVersion: v1
data:
  altGreeting: Red Hat is the best
  enableRisky: "true"
kind: ConfigMap
metadata:
  annotations:
    note: Hello, I am simple-app!
  labels:
    org: acmeCorporation
    variant: simple-app
  name: simple-app-the-map
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am simple-app!
  labels:
    org: acmeCorporation
    variant: simple-app
  name: simple-app-the-service
spec:
  ports:
  - port: 8666
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: hello
    org: acmeCorporation
    variant: simple-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am simple-app!
  labels:
    org: acmeCorporation
    variant: simple-app
  name: simple-app-the-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      deployment: hello
      org: acmeCorporation
      variant: simple-app
  template:
    metadata:
      annotations:
        note: Hello, I am simple-app!
      labels:
        deployment: hello
        org: acmeCorporation
        variant: simple-app
    spec:
      containers:
      - command:
        - /hello
        - --port=8080
        - --enableRiskyFeature=$(ENABLE_RISKY)
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              key: altGreeting
              name: simple-app-the-map
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              key: enableRisky
              name: simple-app-the-map
        image: monopole/hello:1
        name: the-container
        ports:
        - containerPort: 8080
