apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2019-07-11T16:28:39Z"
  generation: 22
  name: stage
  namespace: argocd
  resourceVersion: "14295636"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/staging
  uid: f0646f89-a3f8-11e9-8806-06a26d4a74fa
spec:
  destination:
    namespace: kustomize
    server: https://api.east-1.sysdeseng.com:6443
  project: default
  source:
    kustomize:
      namePrefix: stage-
    path: argocd/overlays/staging
    repoURL: git@github.com:cooktheryan/demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
