apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
spec:
  destination:
    namespace: default
    server: 'https://api.east-1.sysdeseng.com:6443'
  source:
    path: argocd/namespaces
    repoURL: 'git@github.com:cooktheryan/demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
