apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
spec:
  destination:
    namespace: kustomize
    server: 'https://api.east-1.sysdeseng.com:6443'
  source:
    path: argocd/overlays/staging
    repoURL: 'git@github.com:cooktheryan/demo.git'
    targetRevision: HEAD
    kustomize:
      namePrefix: staging-
  project: default
  syncPolicy:
    automated:
      prune: true
